### ISSUE TITLE
Graph reconstruction

### ISSUE THREAD

**Issue by Hmt0** [Google-Health/records-research#10]
I read about the graph reconstruction task in the paper, could you share the code of this part？

**Comment by jonasbkemp** [comment]
@mp2893

**Comment by mp2893** [comment]
Hi Hmt0,

Thanks for taking interest in our work.
Please read [this thread](https://github.com/Google-Health/records-research/issues/3) for the general guideline.

Best,
Ed

**Comment by jonasbkemp** [comment]
Closing this issue, please reopen if you still need assistance and the thread Ed linked doesn't answer your question.
