### ISSUE TITLE
Progress on MUFASA code

### ISSUE THREAD

**Issue by abhishektyaagi** [Google-Health/records-research#12]
Hi,
Congratulations on your work MUFASA.

I was wondering if there is any update on the progress related to the release of the codebase.

The paper mentions that the code will be released soon and I think it would be great for researchers like me to have it

**Comment by abhishektyaagi** [comment]
Thank you for making the MUFASA codebase available.

I was wondering if you have any inputs on what sorts of challenges and/or changes will be required to MUFASA if we intend to use it on a custom dataset

**Comment by jonasbkemp** [comment]
Hi Abhishek, unfortunately the MUFASA code is not actively maintained as the author has left Google. But I hope you've found the code release helpful for your use case!
