### ISSUE TITLE
Recommended instance size and types (memory, CPU) for GCT project

### ISSUE THREAD

**Issue by foadgr** [Google-Health/records-research#14]
Hi @mp2893, would you have any recommendations for instance size and type (memory, CPU) for the data preprocessing and training modules `graph-convolutional-transformer`? Thank you!

**Comment by mp2893** [comment]
Hi @foadgr, it depends on how large your dataset is, in terms of the number of visits, and the number of events (e.g. diagnosis, prescription, lab, etc) per visit.
Preprocessing-wise, unless you are planning to use parallel processing, I don't think CPU/memory types would matter much. The larger the dataset, the longer the preprocessing will take. (Fortunately, you only need to do it once :))
Training-wise, unless you are planning to use data-parallelism or model-parallelism, any decent GPU with 24GB VRAM will suffice. If you are dealing with outpatient records (which typically have less than 100 events per visit), 12GB VRAM would also work. If you are dealing with ICU records (which have thousands or more events per visit), you might need 48GB VRAM.

Best,
Ed

**Comment by foadgr** [comment]
Thank you! Was able to successfully run the eICU data on Fold 0 after some modifications to Python and TF versions. Closing this ticket.
