### ISSUE TITLE
I could not find the treatment.csv in eICU dataset 

### ISSUE THREAD

**Issue by jeremykid** [Google-Health/records-research#2]
In wiki: 

> Download the patient, admissionDx, diagnosis, treatment CSV files.

I get the permission in MIMIC-III Clinical Database(version 1.4)

1. I found several diagnosis.csv files. I don't know which is the correct one.
2. I could not find any treatment.csv files. Is this related to the procedure files?  

Could you help me with this? Thank you so much.

**Comment by mp2893** [comment]
Hi jeremykid

you should download eICU, not MIMIC-III. 

Best
Ed

**Comment by jeremykid** [comment]
Thank you so much, I got it.
