### ISSUE TITLE
Could you provide a toy example about the eICU dataset

### ISSUE THREAD

**Issue by YuMiaoTHU** [Google-Health/records-research#5]
It is an excellent work!!!
It is very useful for me!
However, It takes a lot of steps for me to download the eICU dataset，Could you provide a toy example of the dataset? Or an example of input tfrecord? I want to run this code to apply to my work.
Thanks for your reply

**Comment by mp2893** [comment]
We've provided the synthetic examples just for the occasion.
Please follow the steps described in the README, which begins with downloading visit_list.p.

Best,
Ed

**Comment by jonasbkemp** [comment]
Duplicate of #3
