### ISSUE TITLE
predict

### ISSUE THREAD

**Issue by liuxiaocong20** [Google-Health/records-research#7]
how to predict？

**Comment by jonasbkemp** [comment]
Can you elaborate on your issue? What are you having trouble predicting?

**Comment by liuxiaocong20** [comment]
> Can you elaborate on your issue? What are you having trouble predicting?

Thank you very much for your reply.
I have  difficulty in getting the true label when calculating the AUC. And why does the prediction  have 40 return values when the batch size is 32?

**Comment by jonasbkemp** [comment]
Closing this issue as stale, please reopen if you still need assistance.
