### ISSUE TITLE
GCT training error

### ISSUE THREAD

**Issue by iliasprc** [Google-Health/records-research#8]
Hi, I am trying to train GCT on synthetic data but I get the following error

tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Context feature 'label.expired' is required but could not be found.
         [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}}]]
         [[node IteratorGetNext (defined at /home/iliask/PycharmProjects/graph-convolutional-transformer/graph_convolutional_transformer.py:615) ]]
         [[node DeserializeSparse_3 (defined at /home/iliask/PycharmProjects/graph-convolutional-transformer/graph_convolutional_transformer.py:615) ]]

**Comment by jonasbkemp** [comment]
Hi Ilias, Issue #3 includes some discussion of how the code must be modified to run on the synthetic samples. Likely you'll need to use a different label. Does this answer your question?

**Comment by jonasbkemp** [comment]
Closing this issue as stale. Please reopen if you still need assistance and the other thread doesn't answer your question.
