### ISSUE TITLE
preprocessing code for MIMIC-III?

### ISSUE THREAD

**Issue by whaleloops** [Google-Health/records-research#9]
Hi, could you release the preprocessing code for MIMIC-III described in this paper:
https://graphreason.github.io/papers/38.pdf

**Comment by jonasbkemp** [comment]
While we unfortunately can't release the preprocessing code directly, preprocessed SequenceExamples compatible with Tensorflow code are available at https://physionet.org/content/mimic-seqex/1.0.0/.
